config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'devise/user_registrations' }
  devise_for :admins

  root 'common/events#index'
  
  get '/admins', to: redirect('/admins/events')
  namespace :admins do
    resources :events
    resources :users
    resources :tickets
    resources :refunds
    post 'refund/:id/verify' => 'refunds#verify', as: :verify_refund
  end

  get '/users', to: redirect('/users/tickets')
  namespace :users do
    resources :tickets
    get 'events' => 'events#index', as: :events
    post 'events/:id/order_tickets' => 'tickets#order_tickets', as: :order_tickets
    post 'events/:id/purchase_tickets' => 'tickets#purchase_tickets', as: :purchase_tickets
    post 'tickets/:id/return' => 'tickets#return_ticket', as: :return_ticket
  end

  scope module: 'common' do
    get 'events' => 'events#index', as: :events
    post 'events' => 'events#index', as: :filter_events
    get 'events/:id' => 'events#show', as: :event
  end

end

app/models/refund.rb
class Refund < ApplicationRecord
  belongs_to :ticket
  belongs_to :user
end

app/controllers/admins/refunds_controller.rb
module Admins
  class RefundsController < AdminController
    before_action :set_refund, only: [:show, :edit, :update, :destroy, :verify]
  
    # GET /refunds
    # GET /refunds.json
    def index
      @refundRequests = Refund.where(verified: false)
      @verifiedRequests = Refund.where(verified: true)
    end
  
    # GET /refunds/1
    # GET /refunds/1.json
    def show
    end
  
    # GET /refunds/new
    def new
      @refund = Refund.new
    end
  
    # GET /refunds/1/edit
    def edit
    end

    # POST - verify ticket
    def verify
      @refund.verified = true
      @refund.save

      @ticket = @refund.ticket
      @ticket.user = nil
      @ticket.save

      respond_to do |format|
        format.html { redirect_to admins_refunds_path, notice: 'Refund verified' }
      end
    end
  
    # POST /refunds
    # POST /refunds.json
    def create
      @refund = Refund.new(refund_params)
  
      respond_to do |format|
        if @refund.save
          format.html { redirect_to admins_refund_path(@refund), notice: 'Refund was successfully created.' }
          format.json { render :show, status: :created, location: @refund }
        else
          format.html { render :new }
          format.json { render json: @refund.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /refunds/1
    # PATCH/PUT /refunds/1.json
    def update
      respond_to do |format|
        if @refund.update(refund_params)
          format.html { redirect_to admins_refund_path(@refund), notice: 'Refund was successfully updated.' }
          format.json { render :show, status: :ok, location: @refund }
        else
          format.html { render :edit }
          format.json { render json: @refund.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /refunds/1
    # DELETE /refunds/1.json
    def destroy
      @refund.destroy
      respond_to do |format|
        format.html { redirect_to admins_refunds_url, notice: 'Refund was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_refund
        @refund = Refund.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def refund_params
        params.require(:refund).permit(:ticket_id, :user_id)
      end
  end  
end

app/helpers/refunds_helper.rb
module RefundsHelper
end

app/views/admins/refunds/index.html.erb
<h1>Refund requests</h1>

<div class="container">
  <div class="row">
    <table class="table table-striped">
      <tr>
        <th>Event</th>
        <th>Ticket</th>
        <th>User</th>
        <th>Refund percentage</th>
        <th>Refund</th>
        <th colspan="2"></th>
      </tr>
      <% @refundRequests.each do |refund| %>
        <tr>
            <td><%= link_to refund.ticket.event.name, admins_event_path(refund.ticket.event) %></td>
            <td><%= link_to refund.ticket.seat_id, admins_ticket_path(refund.ticket) %></td>
            <td><%= link_to refund.user.email, admins_user_path(refund.user) %></td>
            <td><%= refund.percents %></td>
            <td><%= refund.price %></td>

            <td><%= link_to 'Verify', admins_verify_refund_path(refund), class: 'btn btn-outline-success', method: :post %></td>
            <td><%= link_to 'Remove', admins_refund_path(refund), method: :delete, 
                                data:{ confirm: 'Are you sure?'}, class: 'btn btn-outline-danger' %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>


<h1>Verified requests</h1>

<div class="container">
    <div class="row">
      <table class="table table-striped">
        <tr>
          <th>Event</th>
          <th>Ticket</th>
          <th>User</th>
          <th>Refund percentage</th>
          <th>Refund</th>
        </tr>
        <% @verifiedRequests.each do |refund| %>
          <tr>
              <td><%= link_to refund.ticket.event.name, admins_event_path(refund.ticket.event) %></td>
              <td><%= link_to refund.ticket.seat_id, admins_ticket_path(refund.ticket) %></td>
              <td><%= link_to refund.user.email, admins_user_path(refund.user) %></td>
              <td><%= refund.percents %></td>
              <td><%= refund.price %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>