config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'devise/user_registrations' }
  devise_for :admins

  root 'common/events#index'
  
  get '/admins', to: redirect('/admins/events')
  namespace :admins do
    resources :events
    resources :users
    resources :tickets
    resources :refunds
    post 'refund/:id/verify' => 'refunds#verify', as: :verify_refund
  end

  get '/users', to: redirect('/users/tickets')
  namespace :users do
    resources :tickets
    get 'events' => 'events#index', as: :events
    post 'events/:id/order_tickets' => 'tickets#order_tickets', as: :order_tickets
    post 'events/:id/purchase_tickets' => 'tickets#purchase_tickets', as: :purchase_tickets
    post 'tickets/:id/return' => 'tickets#return_ticket', as: :return_ticket
  end

  scope module: 'common' do
    get 'events' => 'events#index', as: :events
    post 'events' => 'events#index', as: :filter_events
    get 'events/:id' => 'events#show', as: :event
  end

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :event

  validates :price, presence: true

end

app/controllers/admins/tickets_controller.rb
module Admins
  class TicketsController < AdminController
    before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  
    # GET /tickets
    # GET /tickets.json
    def index
      @allTickets = Ticket.all
      @activeTickets = @allTickets.select{ |ticket| ticket.event[:event_date] > Date.today - 1.day }
      @expiredTickets =  @allTickets.select{ |ticket| ticket.event[:event_date] < Date.today - 1.day }     
    end
  
    # GET /tickets/1
    # GET /tickets/1.json
    def show
    end
  
    # GET /tickets/new
    def new
      @ticket = Ticket.new
      @ticket.event_id = params[:eventId]
    end
  
    # GET /tickets/1/edit
    def edit
    end
  

    # POST /tickets
    # POST /tickets.json
    def create
      @ticket = Ticket.new(ticket_params)
  
      respond_to do |format|
        if @ticket.save
          format.html { redirect_to admins_event_path(@ticket.event_id), notice: 'Ticket was successfully created.' }
          format.json { render :show, status: :created, location: @ticket }
        else
          format.html { render :new }
          format.json { render json: @ticket.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /tickets/1
    # PATCH/PUT /tickets/1.json
    def update
      respond_to do |format|
        if @ticket.update(ticket_params)
          format.html { redirect_to admins_tickets_path, notice: 'Ticket was successfully updated.' }
          format.json { render :show, status: :ok, location: @ticket }
        else
          format.html { render :edit }
          format.json { render json: @ticket.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /tickets/1
    # DELETE /tickets/1.json
    def destroy
      @ticket.destroy
      respond_to do |format|
        format.html { redirect_to admins_tickets_path, notice: 'Ticket was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_ticket
        @ticket = Ticket.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def ticket_params
        params.require(:ticket).permit(:seat_id, :price, :user_id, :event_id)
      end
  end  
end

app/controllers/users/tickets_controller.rb
module Users
  class TicketsController < UserController
  
    # GET /tickets
    # GET /tickets.json
    def index
      @allTickets = Ticket.where(user: current_user)
      @activeTickets = @allTickets.select{ |ticket| ticket.event[:event_date] > Date.today - 1.day }
      @expiredTickets =  @allTickets.select{ |ticket| ticket.event[:event_date] < Date.today - 1.day }     
    end

    # GET
    def order_tickets
      if(params[:selected_tickets] == nil)
        redirect_to event_path(params[:id]), notice: 'Select tickets.'
      elsif(params[:selected_tickets].length > 5)
        redirect_to event_path(params[:id]), notice: 'You can select max 5 tickets.'
      elsif(params[:selected_tickets].length + Ticket.where(user: current_user, event: params[:id]).length > 5)
        redirect_to event_path(params[:id]), notice: 'You can buy max 5 tickets on single event.'
      else
        @selected_tickets = Ticket.where(id: params[:selected_tickets])
      end
    end

    #POST
    def purchase_tickets
      @selected_tickets = Ticket.where(id: params[:selected_tickets])
      @selected_tickets.each do |ticket|
        ticket.user = current_user
        ticket.save
      end
      respond_to do |format|
        format.html { redirect_to events_path, notice: 'Ticket bought.' }
      end
    end

    # POST
    def return_ticket
      @ticket = Ticket.find(params[:id])
      @refund = Refund.new
      @refund.user = current_user
      @refund.ticket = @ticket

      publishing_duration_days = @ticket.event.event_date.minus_with_duration(@ticket.event["created_at"].to_datetime).round
      days_to_event = @ticket.event.event_date.minus_with_duration(Date.today).round
      days_to_event_in_percentage = 100 * days_to_event / publishing_duration_days

      @refund.percents = 100 - ((100 - days_to_event_in_percentage)/2 + 10)
      @refund.price = @refund.percents * @ticket.price / 100
      
      @refund.save

      respond_to do |format|
        format.html { redirect_to users_tickets_path, notice: 'Ticket refund request sent. Refund have to be accepted by administrator.' }
      end
    end
    
  end  
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admins/tickets/_form.html.erb
<%= form_with(model: ticket, local: true, url:url) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :seat_id %>
    <%= form.text_field :seat_id, id: :ticket_seat_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, id: :ticket_price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :ticket_user_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :event_id %>
    <%= form.text_field :event_id, id: :ticket_event_id, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: 'btn btn-outline-success'  %>
  </div>
<% end %>

app/views/admins/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket, url: admins_ticket_url(@ticket) %>

<%= link_to 'Back', admins_ticket_path, class: 'btn btn-outline-warning' %>

app/views/admins/tickets/index.html.erb
<div class="btn-add">
    <%= link_to 'New ticket', new_admins_ticket_path, class: 'btn btn-lg btn-primary' %>
</div>

<h1>Active tickets</h1>

<div class="container">
    <div class="row">
      <table class="table table-striped">
        <tr>
          <th>Seat</th>
          <th>Event</th>
          <th>Price</th>
          <th colspan="3">User</th>
        </tr>
        <% @activeTickets.each do |ticket| %>
          <tr>
              <td><%= link_to ticket.seat_id, admins_ticket_path(ticket) %></td>
              <td><%= link_to ticket.event.name, admins_event_path(ticket.event) %></td>
              <td><%= ticket.price %></td>
              <% if ticket.user.nil? %>
                <td><%= ticket.user %></td>
              <% else %>
                <td><%= ticket.user.email %></td>
              <% end %>
              <td><%= link_to 'Edit', edit_admins_ticket_path(ticket), class: 'btn btn-outline-warning' %></td>
              <td><%= link_to 'Remove', admins_ticket_path(ticket), method: :delete, 
                                  data:{ confirm: 'Are you sure?'}, class: 'btn btn-outline-danger' %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <h1>Expired tickets</h1>
  
  <div class="container">
    <div class="row">
      <table class="table table-striped">
        <tr>
          <th>Seat</th>
          <th>Event</th>
          <th>Price</th>
          <th colspan="3">User</th>
        </tr>
        <% @expiredTickets.each do |ticket| %>
          <tr>
              <td><%= link_to ticket.seat_id, admins_ticket_path(ticket) %></td>
              <td><%= link_to ticket.event.name, admins_event_path(ticket.event) %></td>
              <td><%= ticket.price %></td>
              <% if ticket.user.nil? %>
                <td><%= ticket.user %></td>
              <% else %>
                <td><%= ticket.user.email %></td>
              <% end %>
              <td><%= link_to 'Edit', edit_admins_ticket_path(ticket), class: 'btn btn-outline-warning' %></td>
              <td><%= link_to 'Remove', admins_ticket_path(ticket), method: :delete, 
                                  data:{ confirm: 'Are you sure?'}, class: 'btn btn-outline-danger' %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  
  
  
  

app/views/admins/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket, url: admins_tickets_url %>

<% if @ticket.event_id.nil? %>
    <%= link_to 'Back', admins_tickets_path, class: 'btn btn-outline-warning' %>
<% else %>
    <%= link_to 'Back', admins_event_path(@ticket.event_id), class: 'btn btn-outline-warning' %>
<% end %>

app/views/admins/tickets/show.html.erb
<p>
  <strong>Seat:</strong>
  <%= @ticket.seat_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ticket.price %>
</p>

<p>
  <strong>User:</strong>
  <%= @ticket.user %>
</p>

<p>
  <strong>Event:</strong>
  <%= @ticket.event.name %>
</p>

<%= link_to 'Edit', edit_admins_ticket_path(@ticket), class: 'btn btn-outline-primary' %>
<%= link_to 'Back', admins_tickets_path, class: 'btn btn-outline-warning' %>