config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'devise/user_registrations' }
  devise_for :admins

  root 'common/events#index'
  
  get '/admins', to: redirect('/admins/events')
  namespace :admins do
    resources :events
    resources :users
    resources :tickets
    resources :refunds
    post 'refund/:id/verify' => 'refunds#verify', as: :verify_refund
  end

  get '/users', to: redirect('/users/tickets')
  namespace :users do
    resources :tickets
    get 'events' => 'events#index', as: :events
    post 'events/:id/order_tickets' => 'tickets#order_tickets', as: :order_tickets
    post 'events/:id/purchase_tickets' => 'tickets#purchase_tickets', as: :purchase_tickets
    post 'tickets/:id/return' => 'tickets#return_ticket', as: :return_ticket
  end

  scope module: 'common' do
    get 'events' => 'events#index', as: :events
    post 'events' => 'events#index', as: :filter_events
    get 'events/:id' => 'events#show', as: :event
  end

end

app/models/event.rb
class Event < ApplicationRecord
    has_many :tickets, dependent: :delete_all

    validates :name, presence: true, length: {minimum: 3, maximum: 150}
    validates :event_date, presence: true
    validate :tickets_publishing_cannot_be_in_the_past 
    validate :tickets_publishing_cannot_be_after_event_date
    validate :event_date_cannot_be_in_the_past

    def tickets_publishing_cannot_be_in_the_past
      if published.present? && published < Date.today
        errors.add(:published, "can't be in the past.")
      end
    end

    def event_date_cannot_be_in_the_past
        if event_date.present? && event_date < Date.today
          errors.add(:event_date, "can't be in the past.")
        end
      end
    
    def tickets_publishing_cannot_be_after_event_date
        if published.present? && published > event_date
          errors.add(:published, "have to be before event date.")
        end
      end    
end

app/controllers/admins/events_controller.rb
module Admins
  class EventsController < AdminController
    before_action :set_event, only: [:show, :edit, :update, :destroy]
  
    # GET /events
    # GET /events.json
    def index
      @incomingEvents = Event.where('event_date > ?', Date.today - 1.day)
      @expiredEvents = Event.where('event_date < ?', Date.today - 1.day)
    end
  
    # GET /events/1
    # GET /events/1.json
    def show
    end
  
    # GET /events/new
    def new
      @event = Event.new
    end
  
    # GET /events/1/edit
    def edit
    end

    def addTicket
      puts('HELLO')
    end
  
    # POST /events
    # POST /events.json
    def create
      @event = Event.new(event_params)
  
      respond_to do |format|
        if @event.save
          format.html { redirect_to admins_event_path(@event), notice: 'Event was successfully created.' }
          format.json { render :show, status: :created, location: @event }
        else
          format.html { render :new }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /events/1
    # PATCH/PUT /events/1.json
    def update
      respond_to do |format|
        if @event.update(event_params)
          format.html { redirect_to admins_event_path(@event), notice: 'Event was successfully updated.' }
          format.json { render :show, status: :ok, location: @event }
        else
          format.html { render :edit }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /events/1
    # DELETE /events/1.json
    def destroy
      @event.destroy
      respond_to do |format|
        format.html { redirect_to admins_events_url, notice: 'Event was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_event
        @event = Event.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def event_params
        params.require(:event).permit(:name, :photo, :description, :minAge, :published, :event_date)
      end
  end  
end

app/controllers/common/events_controller.rb
module Common
  class EventsController < CommonController

    # GET/POST /events
    # GET/POST /events.json
    def index
      if request.post?
        dateFilters = params[:date_filter]
        @from = dateFilters[:from]
        @to = dateFilters[:to]
        if ( @from.present? && @to.present? )
          @events = Event.where('event_date between (?) and (?)', @from, @to).order(:event_date => :desc)
        else
          @events = Event.where('event_date > ?', Date.today - 1.day).order(:event_date => :asc)
        end
      else
        @events = Event.where('event_date > ?', Date.today - 1.day).order(:event_date => :asc)
      end
    end

    # GET /events/1
    # GET /events/1.json
    def show
      @event = Event.find(params[:id])
    end
  
  end  
end

app/controllers/users/events_controller.rb
module Users
  class EventsController < UserController
  
    # GET /events
    # GET /events.json
    def index
      @allEvents = Ticket.where(user: current_user).map {|ticket| ticket.event}.uniq! {|e| e }
      @incomingEvents = @allEvents.select{ |event| event[:event_date] > Date.today - 1.day }
      @expiredEvents =  @allEvents.select{ |event| event[:event_date] < Date.today - 1.day }
    end

  end  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admins/events/_event.html.erb
<tr>
    <td><%= link_to event.name, admins_event_path(event) %></td>
    <td></td>
    <td><%= link_to 'Edit', edit_admins_event_path(event), class: 'btn btn-outline-warning' %></td>
    <td><%= link_to 'Remove', admins_event_path(event), method: :delete, 
                        data:{ confirm: 'Are you sure?'}, class: 'btn btn-outline-danger' %></td>
</tr>

app/views/admins/events/_form.html.erb
<%= form_with(model: event, local: true, url:url) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :event_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :photo %>
    <%= form.text_field :photo, id: :event_photo, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :event_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :minimal_age %>
    <%= form.number_field :minAge, id: :event_minAge, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :tickets_publishing %>
    <%= form.date_field :published, id: :event_published, :include_blank => true, class: 'form-control' %>

  </div>

  <div class="form-group">
    <%= form.label :event_date %>
    <%= form.date_field :event_date, id: :event_event_date, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: 'btn btn-outline-success' %>
  </div>
<% end %>

app/views/admins/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event, url: admins_event_url(@event) %>

<%= link_to 'Back', admins_events_path, class: 'btn btn-outline-warning' %>

app/views/admins/events/index.html.erb
<div class="btn-add">
    <%= link_to 'New event', new_admins_event_path, class: 'btn btn-lg btn-primary' %>
</div>

<h1>Incoming events</h1>

<div class="container">
  <div class="row">
    <table class="table table-striped">
      <tr>
        <th colspan="4">Event</th>
      </tr>
      <% @incomingEvents.each do |event| %>
          <%= render event %>
      <% end %>
    </table>
  </div>
</div>

<h1>Expired events</h1>

<div class="container">
  <div class="row">
    <table class="table table-striped">
      <tr>
        <th colspan="4">Event</th>
      </tr>
      <% @expiredEvents.each do |event| %>
          <%= render event %>
      <% end %>
    </table>
  </div>
</div>

app/views/admins/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event, url: admins_events_url %>

<%= link_to 'Back', admins_events_path, class: 'btn btn-outline-warning' %>

app/views/admins/events/show.html.erb
<div class="crop">
  <img src=<%= @event.photo %> style="width: 100%">
</div>
  
<h2>
  <%= @event.name %>
</h2>

<p>
  <%= @event.description %>
</p>

<p>
  <strong>Minimal age:</strong>
  <%= @event.minAge %>
</p>

<p>
  <strong>Tickets publishing:</strong>
  <%= @event.published %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event.event_date %>
</p>

<div>
  <div class="btn-add">
    <%= link_to 'Add ticket', new_admins_ticket_path(eventId: @event.id), class: 'btn btn-primary' %>
  </div>
  <table class="table table-striped">
    <tr>
      <th>Seat</th>
      <th>Price</th>
      <th colspan="3">User</th>
    </tr>
    <% @event.tickets.each do |ticket| %>
      <tr>
        <td><%= link_to ticket.seat_id, admins_ticket_path(ticket) %></td>
        <td><%= ticket.price %></td>
        <td>
          <% if !ticket.user.nil? %>
            <%= ticket.user.email %>
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_admins_ticket_path(ticket), class: 'btn btn-outline-warning' %></td>
        <td><%= link_to 'Remove', admins_ticket_path(ticket), method: :delete, 
                            data:{ confirm: 'Are you sure?'}, class: 'btn btn-outline-danger' %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to 'Edit event', edit_admins_event_path(@event), class: 'btn btn-outline-primary' %>
<%= link_to 'Remove', admins_event_path(@event), method: :delete, 
                    data:{ confirm: 'Are you sure?'}, class: 'btn btn-outline-danger' %>
<%= link_to 'Back', admins_events_path, class: 'btn btn-outline-warning' %>