config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'devise/user_registrations' }
  devise_for :admins

  root 'common/events#index'
  
  get '/admins', to: redirect('/admins/events')
  namespace :admins do
    resources :events
    resources :users
    resources :tickets
    resources :refunds
    post 'refund/:id/verify' => 'refunds#verify', as: :verify_refund
  end

  get '/users', to: redirect('/users/tickets')
  namespace :users do
    resources :tickets
    get 'events' => 'events#index', as: :events
    post 'events/:id/order_tickets' => 'tickets#order_tickets', as: :order_tickets
    post 'events/:id/purchase_tickets' => 'tickets#purchase_tickets', as: :purchase_tickets
    post 'tickets/:id/return' => 'tickets#return_ticket', as: :return_ticket
  end

  scope module: 'common' do
    get 'events' => 'events#index', as: :events
    post 'events' => 'events#index', as: :filter_events
    get 'events/:id' => 'events#show', as: :event
  end

end

app/views/layouts/_admin_navbar.html.erb
<nav class="navbar app-navbar navbar-expand-lg">
    
    <%= link_to 'Events', admins_events_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%= link_to 'Tickets', admins_tickets_path, class: 'btn navbar-btn app-navbar-button'  %>
            </li>    
            <li class="nav-item">
                <%= link_to 'Refunds', admins_refunds_path, class: 'btn navbar-btn app-navbar-button'  %>
            </li> 
            <li class="nav-item">
                <%= link_to 'Users', admins_users_path, class: 'btn navbar-btn app-navbar-button'  %>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <%= link_to 'Logout', destroy_admin_session_path, method: :delete, class: 'btn navbar-btn app-navbar-button'  %>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/_common_navbar.html.erb
<nav class="navbar app-navbar navbar-expand-lg">

    <%= link_to 'Events', events_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to 'Tickets', users_tickets_path, class: 'btn navbar-btn app-navbar-button' %>
                </li>  
                <li class="nav-item">
                    <%= link_to 'My events', users_events_path, class: 'btn navbar-btn app-navbar-button' %>
                </li>     
            <% end %>    
        </ul>
        <ul class="navbar-nav">
            <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn navbar-btn app-navbar-button' %>
                </li>
            <% else %>  
                <li class="nav-item">
                    <%= link_to 'Login', new_user_session_path, class: 'btn navbar-btn app-navbar-button' %>
                </li>
            <% end %>  
        </ul>
    </div>
</nav>

app/views/layouts/_devise_navbar.html.erb
<nav class="navbar app-navbar navbar-expand-lg">
    <%= link_to 'Events', events_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="app-top">
        <%= render 'layouts/admin_navbar' %>
      </div>
    <div class="app-content">
      <% if notice.present? %>
        <div class="alert alert-success">
          <%= notice %>
        </div>
      <% end %>
      <%= yield %>    
    </div>
  </body>
</html>

app/views/layouts/common.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="app-top">
        <%= render 'layouts/common_navbar' %>
    </div>
    <div class="app-content">
      <% if notice.present? %>
        <div class="alert alert-success">
          <%= notice %>
        </div>
      <% end %>
      <%= yield %>    
    </div>

  </body>
</html>

app/views/layouts/devise_auth.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="app-top">
        <%= render 'layouts/devise_navbar' %>
      </div>
    <div class="app-content">
      <% if notice.present? %>
        <div class="alert alert-success">
          <%= notice %>
        </div>
      <% end %>
      <%= yield %>    
    </div>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="app-top">
        <%= render 'layouts/common_navbar' %>
      </div>
    <div class="app-content">
      <% if notice.present? %>
        <div class="alert alert-success">
          <%= notice %>
        </div>
      <% end %>
      <%= yield %>    
    </div>
  </body>
</html>